name: Hassfest

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: hassfest-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v7
      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
